### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by jasonkalmeida** [techforwarren/eventmap#15]
Details to be added, but essentially have an idea for a modified UX for mobile.

**Comment by danielnarey** [comment]
Tested the app on an iPhone SE - not sure what you’re thinking, but I think it would work visually to make the event info box a fixed header that occupies the top third of the viewport with no top or left/right margins.

**Comment by jasonkalmeida** [comment]
The search on my local dev for mobile is fixed as you suggested.

My current implementation strategy is something similar to what Yelp does with its multiple cards on mobile.

![image_from_ios](https://user-images.githubusercontent.com/5836378/66107320-cffde200-e574-11e9-9cd6-1aaa5e41fa33.jpg)
