### ISSUE TITLE
Link Preview Image [Design Input Needed!]

### ISSUE THREAD

**Issue by jasonkalmeida** [techforwarren/eventmap#17]
When a user posts a link on a social media site/platform, there generally is an associated preview image/thumbnail. We should probably think of what we want the Event Map's to be.

**Comment by danielnarey** [comment]
Created social media preview image at 1280 x 640: https://github.com/techforwarren/design-assets/tree/master/event-map/social-preview

Let me know if you think this would work and if smaller versions are needed as well.
