### ISSUE TITLE
Configure Inertia Scrolling

### ISSUE THREAD

**Issue by jasonkalmeida** [techforwarren/eventmap#19]
via Joe: "Right now, if I two-finger scroll on my mac to zoom in, the zooming continues for another few levels, which makes it harder to use. IIRC there are some ways to turn off inertia scrolling"

This should be researched, and at the very least modified on desktop!

**Comment by bnaikcekr** [comment]
Pull Request Opened!

**Comment by joegoldbeck** [comment]
Is this closed by #51?

**Comment by joegoldbeck** [comment]
Is this closed by #51?

**Comment by jasonkalmeida** [comment]
Yup!
