### ISSUE TITLE
Add Zip Code to the URL

### ISSUE THREAD

**Issue by joegoldbeck** [techforwarren/eventmap#24]
Link the url params to the search being done. This would serve the purposes of

- Allowing a user to share a link with someone else, showing the events in that other persons' area
- Make a search bookmarkable
- Allowing "the bot" to share a link if someone asks for it
- It could also be used in conjunction with history to give good back button behavior

**Comment by jlev** [comment]
+1 using the History API for this. Makes for much nicer URLs, and the data persistence is a plus.

**Comment by jlev** [comment]
initial implementation using just history API

getting back button to work requires react-router-dom, which might feel like overkill for this SPA

**Comment by jlev** [comment]
Seeing this deployed made me realize that we can't just push '/?zipcode=' to the history, we need to maintain the current path. Otherwise deployments to different GitHub Pages will break.
