### ISSUE TITLE
Redesign Search Bar To Clarify Options

### ISSUE THREAD

**Issue by jasonkalmeida** [techforwarren/eventmap#44]
Brought up in some feedback on Reddit, the current UI can be a bit confusing - a user might think the geolocation button is a "submit" button for the Zipcode search. Should be redesigned to clearly have the two options (zipcode and geolocation).

**Comment by joziesands** [comment]
Hey!
I don't know if you were looking for someone to do this, but it was my first step in playing with issue  #6. Are you looking for something like this?
![Screen Shot 2019-10-18 at 10 55 48 PM](https://user-images.githubusercontent.com/1656339/67137459-667c0580-f1fb-11e9-98a2-7f82e993c130.png)

**Comment by jasonkalmeida** [comment]
Hey Jozie!

LOVE the clean design here - I’m seeing though in the live version you have that the search automatically runs when a user types in 5 digits?

**Comment by joziesands** [comment]
Oops.. try it now. I'm also not sure what to do with the map view when there aren't any events nearby. My instinct is to return to the full US view, but it's not implemented yet.

**Comment by jasonkalmeida** [comment]
Featured completed by @joziesands
