### ISSUE TITLE
Account for events that are missing latitude or longitude

### ISSUE THREAD

**Issue by litnerdy** [techforwarren/eventmap#53]
Example of what happens when we look up a zipcode that includes an event with a missing latitude: 

https://techforwarren.github.io/eventmap/?zip=94002

"TypeError: Cannot read property 'latitude' of undefined"

**Ideas for solutions:**

-  make sure that even if one event fails, we can still pull the rest. 
- consider showing a small error that tells the user that an event failed to load. If possible, link to that event on the warren site.

**Comment by chief-dweeb** [comment]
I believe that this issue is fixed.  It doesn't fail on zip=94002, but that could be because the events have changed, but in any event - after looking at the code - it appears that there are checks for valid lat/long everywhere, so I am going to close this.
